In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [42]:
data = pd.read_csv(r"C:\Users\ekaushik\OneDrive - DXC Production\Desktop\output_data.csv")

In [10]:
df


# for earned in df['Declined_Transactions']:
#     print(f'earned {earned}')
#     np.random.randint(0, earned/10)

,Age,Agent_ID,Agent_Notes,Annual_Fee,Authorization_Code,Authorization_Status,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,Card_Cancelled,...,Start_Date,Status,Summer_Spending,Survey_Date,Satisfaction_Score,Tax_Amount,Topics_Discussed,Total_Transactions_in_Period,Transaction_Amount,Transaction_Frequency
0,37,7823,None,1.175657,None,None,736.143819,331.616577,None,Yes,...,None,Active,35.570545,None,8,80.979176,None,1,885.583982,9
1,50,8462,None,22.000219,None,None,1423.873063,882.858883,None,No,...,None,Churned,16.960060,None,7,22.088874,None,72,71.951816,5
2,48,8097,None,49.385728,None,None,1813.671005,3383.670765,None,No,...,None,Active,60.981436,None,7,58.917018,None,90,600.013852,4
3,24,4023,None,22.075949,None,None,1280.734728,4589.382787,None,Yes,...,None,Active,24.685547,None,2,28.683354,None,84,653.701416,5
4,47,3074,None,47.607390,None,None,1043.937250,4599.615762,None,No,...,None,Active,18.419668,None,3,33.007019,None,46,969.539683,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,34,9900,None,35.039063,None,None,178.972452,1741.625885,None,No,...,None,Active,7.530969,None,10,5.916057,None,53,2.432743,7
6996,27,7282,None,63.628241,None,None,835.199167,2308.695655,None,No,...,None,Churned,40.148396,None,5,48.492652,None,7,578.804079,8
6997,78,8878,None,97.932039,None,None,800.721898,949.848406,None,Yes,...,None,Churned,22.403579,None,6,17.777429,None,35,243.477085,8
6998,53,9579,None,5.359739,None,None,1177.134934,424.057545,None,No,...,None,Active,41.337156,None,8,49.518698,None,76,640.161536,6
6999,19,9153,None,5.551833,None,None,677.969136,305.213801,None,Yes,...,None,Churned,60.455218,None,1,31.488464,None,89,151.144264,6

In [11]:
# # df.to_excel('gen_data.xlsx',index = False)
# data

In [48]:
import copy
out2 = copy.deepcopy(data)

In [52]:
out2.fillna(method = 'bfill',inplace = True)
out2.fillna(method = 'ffill',inplace = True)
out2.isna().sum()[out2.isna().sum()!=0]

Previous_Interaction_Date     7000
Previous_Resolution_Status    7000
Receipt_ID                    7000
Referral_Source               7000
Response_to_Last_Promotion    7000
Settlement_Date               7000
Survey_Date                   7000
Topics_Discussed              7000
dtype: int64

In [54]:
out2.dropna(axis = 1, how = 'all',inplace = True)

In [58]:
out3 = copy.deepcopy(out2)

In [59]:
out2

,Age,Agent_ID,Agent_Notes,Annual_Fee,Authorization_Code,Authorization_Status,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,Card_Cancelled,...,Total_Transactions_in_Period,Transaction_Amount,Transaction_Frequency,Weekend_vs_Weekday_Spending,num_interactions,Customer_Type,Rule_Matched,Customer_Risk_Level,Churn_rate,churned_revenue
0,29,1994,Note2,71.731720,YGSHHZ,Timeout,347.751406,4058.057533,Cycle3,Yes,...,69,842.911294,8,4,7,High Balancer,Rule 19,Medium,0,0
1,75,9550,Note1,54.938336,FYTU5A,Expired Card,1982.905896,3796.218594,Cycle3,Yes,...,30,757.410427,8,7,16,Loyal User,Rule 12,Low,0,0
2,27,5246,Note3,42.026871,JW2AEZ,Invalid Card,881.517178,2841.821037,Cycle2,No,...,19,993.978411,5,6,13,Loyal User,Rule 12,Low,0,0
3,61,2406,Note1,81.435025,3M8VVR,Timeout,1339.011547,1092.778921,Cycle2,Yes,...,49,20.095073,7,7,8,Inactive,Rule 5,High,0,0
4,31,8285,Note3,25.043256,EU3PUX,Approved,1613.595739,1011.506549,Cycle3,Yes,...,75,674.885406,7,7,12,Inactive,Rule 5,High,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,41,1710,Note1,57.661303,AOLM0D,Declined,545.119118,3630.162933,Cycle3,Yes,...,64,694.691726,9,7,22,Complaint-heavy,Rule 7,High,0,0
6996,18,2866,Note1,3.325314,QYC74J,Referred,1301.673903,748.328523,Cycle1,No,...,67,568.648587,4,6,15,High Balancer,Rule 19,Medium,0,0
6997,76,8668,Note2,58.117482,CO1S4H,Referred,751.353369,581.915195,Cycle1,Yes,...,9,77.263270,7,4,11,Complaint-heavy,Rule 7,High,0,0
6998,65,1583,Note1,46.585127,2X5VZB,Invalid Card,1801.547232,4676.164364,Cycle1,No,...,11,745.172043,7,6,16,Over Utilizer,Rule 3,High,0,0
6999,40,7155,Note1,44.358246,HVG5DK,Insufficient Funds,288.618813,1560.152743,Cycle3,No,...,44,51.421351,6,4,14,Inactive,Rule 5,High,0,0

In [38]:
pip install scikit-learn

^C
Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: scikit-learn in c:\users\ekaushik\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (1.3.1)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\ekaushik\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\ekaushik\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ekaushik\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ekaushik\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scikit-learn) (3.2.0)

In [61]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in out2.select_dtypes(include = 'object'):
    out2[i] = le.fit_transform(out2[i])

In [63]:
X = out2.drop(['Rule_Matched','churned_revenue','Churn_rate','Customer_Type','Customer_Risk_Level'],axis = 1)
y = out2['Customer_Risk_Level']

In [74]:
data['Customer_Risk_Level'].value_counts()

Customer_Risk_Level
High              3880
Low               1905
Medium            1085
Not Applicable     130
Name: count, dtype: int64

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [65]:
from sklearn.ensemble import RandomForestClassifier


from sklearn.metrics import classification_report, confusion_matrix

In [66]:
from sklearn.ensemble import GradientBoostingClassifier

In [67]:
gb=GradientBoostingClassifier(n_estimators=100,random_state=0)
gb.fit(X_train,y_train)

GradientBoostingClassifier(random_state=0)

In [68]:
y_test_pred=gb.predict(X_test)

In [69]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       776
           1       0.99      0.99      0.99       372
           2       0.92      0.98      0.95       223
           3       0.77      0.34      0.48        29

    accuracy                           0.98      1400
   macro avg       0.92      0.83      0.85      1400
weighted avg       0.98      0.98      0.98      1400

In [70]:
#Taking output for whole X dataset
y_pred = gb.predict(X)
y_pred

array([2, 1, 1, ..., 0, 0, 0])

In [71]:
out3

,Age,Agent_ID,Agent_Notes,Annual_Fee,Authorization_Code,Authorization_Status,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,Card_Cancelled,...,Total_Transactions_in_Period,Transaction_Amount,Transaction_Frequency,Weekend_vs_Weekday_Spending,num_interactions,Customer_Type,Rule_Matched,Customer_Risk_Level,Churn_rate,churned_revenue
0,29,1994,Note2,71.731720,YGSHHZ,Timeout,347.751406,4058.057533,Cycle3,Yes,...,69,842.911294,8,4,7,High Balancer,Rule 19,Medium,0,0
1,75,9550,Note1,54.938336,FYTU5A,Expired Card,1982.905896,3796.218594,Cycle3,Yes,...,30,757.410427,8,7,16,Loyal User,Rule 12,Low,0,0
2,27,5246,Note3,42.026871,JW2AEZ,Invalid Card,881.517178,2841.821037,Cycle2,No,...,19,993.978411,5,6,13,Loyal User,Rule 12,Low,0,0
3,61,2406,Note1,81.435025,3M8VVR,Timeout,1339.011547,1092.778921,Cycle2,Yes,...,49,20.095073,7,7,8,Inactive,Rule 5,High,0,0
4,31,8285,Note3,25.043256,EU3PUX,Approved,1613.595739,1011.506549,Cycle3,Yes,...,75,674.885406,7,7,12,Inactive,Rule 5,High,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,41,1710,Note1,57.661303,AOLM0D,Declined,545.119118,3630.162933,Cycle3,Yes,...,64,694.691726,9,7,22,Complaint-heavy,Rule 7,High,0,0
6996,18,2866,Note1,3.325314,QYC74J,Referred,1301.673903,748.328523,Cycle1,No,...,67,568.648587,4,6,15,High Balancer,Rule 19,Medium,0,0
6997,76,8668,Note2,58.117482,CO1S4H,Referred,751.353369,581.915195,Cycle1,Yes,...,9,77.263270,7,4,11,Complaint-heavy,Rule 7,High,0,0
6998,65,1583,Note1,46.585127,2X5VZB,Invalid Card,1801.547232,4676.164364,Cycle1,No,...,11,745.172043,7,6,16,Over Utilizer,Rule 3,High,0,0
6999,40,7155,Note1,44.358246,HVG5DK,Insufficient Funds,288.618813,1560.152743,Cycle3,No,...,44,51.421351,6,4,14,Inactive,Rule 5,High,0,0

In [75]:
#Combining Y_pred with actual X dataset after inverse transforming
le.fit(out3['Customer_Risk_Level'])
predictions = le.inverse_transform(y_pred)
out3['predictions'] = predictions

In [77]:
out3

,Age,Agent_ID,Agent_Notes,Annual_Fee,Authorization_Code,Authorization_Status,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,Card_Cancelled,...,Transaction_Amount,Transaction_Frequency,Weekend_vs_Weekday_Spending,num_interactions,Customer_Type,Rule_Matched,Customer_Risk_Level,Churn_rate,churned_revenue,predictions
0,29,1994,Note2,71.731720,YGSHHZ,Timeout,347.751406,4058.057533,Cycle3,Yes,...,842.911294,8,4,7,High Balancer,Rule 19,Medium,0,0,Medium
1,75,9550,Note1,54.938336,FYTU5A,Expired Card,1982.905896,3796.218594,Cycle3,Yes,...,757.410427,8,7,16,Loyal User,Rule 12,Low,0,0,Low
2,27,5246,Note3,42.026871,JW2AEZ,Invalid Card,881.517178,2841.821037,Cycle2,No,...,993.978411,5,6,13,Loyal User,Rule 12,Low,0,0,Low
3,61,2406,Note1,81.435025,3M8VVR,Timeout,1339.011547,1092.778921,Cycle2,Yes,...,20.095073,7,7,8,Inactive,Rule 5,High,0,0,High
4,31,8285,Note3,25.043256,EU3PUX,Approved,1613.595739,1011.506549,Cycle3,Yes,...,674.885406,7,7,12,Inactive,Rule 5,High,0,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,41,1710,Note1,57.661303,AOLM0D,Declined,545.119118,3630.162933,Cycle3,Yes,...,694.691726,9,7,22,Complaint-heavy,Rule 7,High,0,0,High
6996,18,2866,Note1,3.325314,QYC74J,Referred,1301.673903,748.328523,Cycle1,No,...,568.648587,4,6,15,High Balancer,Rule 19,Medium,0,0,Medium
6997,76,8668,Note2,58.117482,CO1S4H,Referred,751.353369,581.915195,Cycle1,Yes,...,77.263270,7,4,11,Complaint-heavy,Rule 7,High,0,0,High
6998,65,1583,Note1,46.585127,2X5VZB,Invalid Card,1801.547232,4676.164364,Cycle1,No,...,745.172043,7,6,16,Over Utilizer,Rule 3,High,0,0,High
6999,40,7155,Note1,44.358246,HVG5DK,Insufficient Funds,288.618813,1560.152743,Cycle3,No,...,51.421351,6,4,14,Inactive,Rule 5,High,0,0,High

In [78]:
def customer_segmentation(row):
    # Over Utilizers Rules
    if row["Credit_Utilization_Rate"] > 0.8 and row["Payment_Timeliness"] == "Late":
        return "Over Utilizer", "Rule 1", "High"
    elif row["Payment_Timeliness"] == "Late" and row["Outstanding_Debt"] > 4000:
        return "Over Utilizer", "Rule 2", "High"
    elif row["Installment_Plan"] == "Yes" and row["Outstanding_Debt"] > 4000:
        return "Over Utilizer", "Rule 3", "High"

    # Inactive Users Rules
    elif row["Days_Since_Last_Login"] > 25 and row["Open_Email_Rate"] < 0.2:
        return "Inactive", "Rule 4", "High"
    elif row["Interaction_ID_count"] < 2:
        return "Inactive", "Rule 5", "High"
    elif row["Days_Since_Last_Transaction"] > 30 and row["Annual_Fee"] > 80:
        return "Inactive", "Rule 6", "High"

    # Complaint-heavy Users
    elif row["Num_Complaints"] > 5 and (row["Resolution_Status"] == 'Pending' or row["Resolution_Status"] == 'Escalated'):
        return "Complaint-heavy", "Rule 7", "High"
    elif row["Open_Email_Rate"] < 0.2 and row["Days_Since_Last_Login"] > 25 and row["Num_Complaints"] > 5:
        return "Complaint-heavy", "Rule 8", "High"

    # Sporadic Users Rules
    elif row["Weekend_vs_Weekday_Spending"] > 8 and row["Transaction_Frequency"] < 5:
        return "Sporadic", "Rule 9", "Medium"
    elif row["Days_Since_Last_Transaction"] > 300 and row["Annual_Fee"] < 20:
        return "Sporadic", "Rule 10", "Medium"
    elif row["Interaction_ID_count"] == 1 and row["Transaction_Amount"] < 100:
        return "Sporadic", "Rule 11", "Medium"
		
    # Loyal Users Rules
    elif row["Interaction_Frequency"] > 7 and row["Payment_History_Length"] > 5:
        return "Loyal User", "Rule 12", "Low"
    elif row["Reward_Points_Redeemed"] > 500 and row["Satisfaction_Score"] > 7:
        return "Loyal User", "Rule 13", "Low"

    # Financially Conscious Users Rules
    elif row["Credit_Utilization_Rate"] < 0.2 and row["Payment_Timeliness"] == "On Time":
        return "Financially Conscious", "Rule 14", "Low"
    elif row["Payment_to_Income_Ratio"] > 0.5 and row["Outstanding_Debt"] < 1000:
        return "Financially Conscious", "Rule 15", "Low"

    # Reward Maximisers Rules
    elif row["Has_Promotion_Used"] == "Yes" and row["Reward_Points_Redeemed"] > 700:
        return "Reward Maximiser", "Rule 16", "Low"
    elif row["Response_to_Last_Promotion"] == "Response1" and row["Social_Media_Follow"] == "Yes":
        return "Reward Maximiser", "Rule 17", "Low"

    # High Balancers Rules
    elif row["Current_Balance"] > 5000 and row["Payment_Timeliness"] in ['Late', 'Very Late']:
        return "High Balancer", "Rule 18", "Medium"
    elif row["Min_Payment"] < (row["Current_Balance"] * 0.05):
        return "High Balancer", "Rule 19", "Medium"
    elif row["Reward_Points_Earned"] < 10:
        return "High Balancer", "Rule 20", "Medium"

    # Low Engagement Rules
    elif row["Sentiment_Score"] < -0.5 and row["Interaction_ID_count"] < 5:
        return "Low Engagement", "Rule 21", "Medium"
    
    else:
        return "Regular", "None", "Not Applicable"
        
    return customer_type, rule, risk_level

In [80]:
out3['Response_to_Last_Promotion'] = None

In [81]:
out3['Customer_Type'], out3['Rule_Matched'], out3['Customer_Risk_Level'] = zip(*out3.apply(customer_segmentation, axis=1))

In [82]:
out3 = out3.reset_index(drop=False)

In [85]:
out3

,index,Age,Agent_ID,Agent_Notes,Annual_Fee,Authorization_Code,Authorization_Status,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,...,Transaction_Frequency,Weekend_vs_Weekday_Spending,num_interactions,Customer_Type,Rule_Matched,Customer_Risk_Level,Churn_rate,churned_revenue,predictions,Response_to_Last_Promotion
0,0,29,1994,Note2,71.731720,YGSHHZ,Timeout,347.751406,4058.057533,Cycle3,...,8,4,7,High Balancer,Rule 19,Medium,0,0,Medium,None
1,1,75,9550,Note1,54.938336,FYTU5A,Expired Card,1982.905896,3796.218594,Cycle3,...,8,7,16,Loyal User,Rule 12,Low,0,0,Low,None
2,2,27,5246,Note3,42.026871,JW2AEZ,Invalid Card,881.517178,2841.821037,Cycle2,...,5,6,13,Loyal User,Rule 12,Low,0,0,Low,None
3,3,61,2406,Note1,81.435025,3M8VVR,Timeout,1339.011547,1092.778921,Cycle2,...,7,7,8,Inactive,Rule 5,High,0,0,High,None
4,4,31,8285,Note3,25.043256,EU3PUX,Approved,1613.595739,1011.506549,Cycle3,...,7,7,12,Inactive,Rule 5,High,0,0,High,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,41,1710,Note1,57.661303,AOLM0D,Declined,545.119118,3630.162933,Cycle3,...,9,7,22,Complaint-heavy,Rule 7,High,0,0,High,None
6996,6996,18,2866,Note1,3.325314,QYC74J,Referred,1301.673903,748.328523,Cycle1,...,4,6,15,High Balancer,Rule 19,Medium,0,0,Medium,None
6997,6997,76,8668,Note2,58.117482,CO1S4H,Referred,751.353369,581.915195,Cycle1,...,7,4,11,Complaint-heavy,Rule 7,High,0,0,High,None
6998,6998,65,1583,Note1,46.585127,2X5VZB,Invalid Card,1801.547232,4676.164364,Cycle1,...,7,6,16,Over Utilizer,Rule 3,High,0,0,High,None
6999,6999,40,7155,Note1,44.358246,HVG5DK,Insufficient Funds,288.618813,1560.152743,Cycle3,...,6,4,14,Inactive,Rule 5,High,0,0,High,None

In [86]:
out3.to_excel(r'C:\Users\ekaushik\OneDrive - DXC Production\Desktop\Output\modeloutput.xlsx', index=False)

In [87]:
# #import pandas as pd
# #import random

# # Number of samples
# N = 7000  # You can adjust this

# data = []

# for _ in range(N):
#     main_cluster = random.choice(['High-Risk', 'Moderate-Risk', 'Low-Risk'])
#     record = {'Risk_Level': main_cluster}
    
#     if main_cluster == 'High-Risk':
#         sub_cluster = random.choice(['Over-Utilizers', 'Inactive Users', 'Complaint-heavy Users'])
#         record['Cluster'] = sub_cluster

#         # Criteria for Over-Utilizers
#         if sub_cluster == 'Over-Utilizers':
#             criteria = random.choice(['High Credit Utilization', 'Recurrent Late Fee', 'High Installment Usage'])
#             record['Criteria'] = criteria
#             if criteria == 'High Credit Utilization':
#                 record['Credit_Utilization_Rate'] = random.uniform(0.7, 1)
#                 record['Payment_Timeliness'] = 'Late'
#             elif criteria == 'Recurrent Late Fee':
#                 record['Payment_Timeliness'] = 'Late'
#                 record['Outstanding_Debt'] = random.uniform(1000, 10000)
#             elif criteria == 'High Installment Usage':
#                 record['Installment_Plan'] = random.choice(['Frequently', 'Rarely'])
#                 record['Outstanding_Debt'] = random.uniform(1000, 10000)
        
#         # Criteria for Inactive Users
#         elif sub_cluster == 'Inactive Users':
#             criteria = random.choice(['Inactive Online', 'New Users', 'Inactive High Fees'])
#             record['Criteria'] = criteria
#             if criteria == 'Inactive Online':
#                 record['Days_Since_Last_Login'] = random.randint(30, 365)
#                 record['Open_Email_Rate'] = random.uniform(0, 0.2)
#             elif criteria == 'New Users':
#                 record['Customer_Acquisition_Date'] = pd.Timestamp.now() - pd.Timedelta(days=random.randint(0, 30))
#                 record['Interaction_ID_Count'] = random.randint(0, 5)
#             elif criteria == 'Inactive High Fees':
#                 record['Days_Since_Last_Transaction'] = random.randint(30, 365)
#                 record['Annual_Fee'] = random.uniform(100, 500)
        
#         # Criteria for Complaint-heavy Users
#         elif sub_cluster == 'Complaint-heavy Users':
#             criteria = random.choice(['High Complaints', 'Low Digital Engagement'])
#             record['Criteria'] = criteria
#             if criteria == 'High Complaints':
#                 record['Num_Complaints'] = random.randint(5, 50)
#                 record['Resolution_Status'] = random.choice(['Pending', 'Escalated'])
#             elif criteria == 'Low Digital Engagement':
#                 record['Open_Email_Rate'] = random.uniform(0, 0.2)
#                 record['Days_Since_Last_Login'] = random.randint(30, 365)
#                 record['Num_Complaints'] = random.randint(5, 50)
                
#         elif main_cluster == 'Moderate-Risk':
#             sub_cluster = random.choice(['Sporadic Users', 'High Balancers', 'New Users with Low Engagement'])
#             record['Cluster'] = sub_cluster

#         # Criteria for Sporadic Users
#         if sub_cluster == 'Sporadic Users':
#             criteria = random.choice(['Usage on Weekends/Holidays', 'Promo Engagement without Transactions'])
#             record['Criteria'] = criteria
#             if criteria == 'Usage on Weekends/Holidays':
#                 record['Weekend_vs_Weekday_Spending'] = random.uniform(0.7, 1)
#                 record['Holiday_Spending'] = random.uniform(0.7, 1)
#             elif criteria == 'Promo Engagement without Transactions':
#                 record['Promo_Code_Usage'] = random.choice(['Frequently', 'Rarely'])
#                 record['Transaction_Amount'] = random.uniform(0, 50)
#                 record['Transaction_Frequency'] = random.uniform(0, 0.2)

#         # Criteria for High Balancers
#         elif sub_cluster == 'High Balancers':
#             criteria = random.choice(['High Balance, Minimum Payments', 'High Balance, Low Reward Points'])
#             record['Criteria'] = criteria
#             if criteria == 'High Balance, Minimum Payments':
#                 record['Current_Balance'] = random.uniform(1000, 10000)
#                 record['Payment_Timeliness'] = random.choice(['Late', 'Very Late'])
#                 record['Min_Payment'] = random.uniform(0, 100)
#             elif criteria == 'High Balance, Low Reward Points':
#                 record['Current_Balance'] = random.uniform(1000, 10000)
#                 record['Reward_Points_Earned'] = random.uniform(0, 20)

#         # Criteria for New Users with Low Engagement
#         elif sub_cluster == 'New Users with Low Engagement':
#             record['Sentiment_Score'] = random.uniform(-1, 0) # Negative sentiment score
#             record['Interaction_ID_Count'] = random.randint(5, 50)
#             record['Resolution_Status'] = random.choice(['Pending', 'Escalated'])
    
#         elif main_cluster == 'Low-Risk':
#              sub_cluster = random.choice(['Loyal Users', 'Financially Conscious Users', 'Reward Maximisers'])
#              record['Cluster'] = sub_cluster

#         # Criteria for Loyal Users
#         if sub_cluster == 'Loyal Users':
#             criteria = random.choice(['High Transaction, Low Reward Redemption', 'Infrequent Usage, High Credit Limit'])
#             record['Criteria'] = criteria
#             if criteria == 'High Transaction, Low Reward Redemption':
#                 record['Transaction_Amount'] = random.uniform(100, 1000)
#                 record['Reward_Points_Redeemed'] = random.uniform(0, 20)
#             elif criteria == 'Infrequent Usage, High Credit Limit':
#                 record['Transaction_Frequency'] = random.uniform(0, 0.2)
#                 record['Max_Credit_Limit'] = random.uniform(1000, 10000)

#         # Criteria for Financially Conscious Users
#         elif sub_cluster == 'Financially Conscious Users':
#             record['Communication_Preference_Updates'] = random.randint(5, 50)

#         # Criteria for Reward Maximisers
#         elif sub_cluster == 'Reward Maximisers':
#             record['Transaction_Amount_Sales_Period'] = random.uniform(100, 1000)
#             record['Promo_Code_Usage'] = 'None'
#             record['Discount_Applied'] = random.uniform(0, 0.2)
			
#     data.append(record)

# df = pd.DataFrame(data)
# df.to_csv('risk_clusters.csv', index=False)

In [ ]:
df

,Risk_Level,Cluster,Criteria,Payment_Timeliness,Outstanding_Debt,Open_Email_Rate,Days_Since_Last_Login,Num_Complaints,Days_Since_Last_Transaction,Annual_Fee,Resolution_Status,Credit_Utilization_Rate,Installment_Plan,Customer_Acquisition_Date,Interaction_ID_Count
0,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,High-Risk,Over-Utilizers,Recurrent Late Fee,Late,3140.973068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,High-Risk,Over-Utilizers,High Credit Utilization,Late,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.80457,NaN,NaT,NaN
6996,High-Risk,Complaint-heavy Users,Low Digital Engagement,NaN,NaN,0.068839,314.0,46.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6997,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6998,High-Risk,Complaint-heavy Users,Low Digital Engagement,NaN,NaN,0.021831,258.0,28.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6999,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
df.isnull().sum()

Risk_Level                        0
Cluster                        4613
Criteria                       4613
Payment_Timeliness             6489
Outstanding_Debt               6521
Open_Email_Rate                6353
Days_Since_Last_Login          6353
Num_Complaints                 6184
Days_Since_Last_Transaction    6737
Annual_Fee                     6737
Resolution_Status              6570
Credit_Utilization_Rate        6722
Installment_Plan               6754
Customer_Acquisition_Date      6710
Interaction_ID_Count           6710
dtype: int64

In [ ]:
df

,Risk_Level,Cluster,Criteria,Days_Since_Last_Login,Open_Email_Rate,Num_Complaints,Resolution_Status,Payment_Timeliness,Outstanding_Debt,Installment_Plan,Customer_Acquisition_Date,Interaction_ID_Count,Credit_Utilization_Rate,Days_Since_Last_Transaction,Annual_Fee
0,High-Risk,Inactive Users,Inactive Online,162.0,0.039916,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
1,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
2,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
3,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
4,High-Risk,Complaint-heavy Users,High Complaints,NaN,NaN,24.0,Pending,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6996,High-Risk,Complaint-heavy Users,High Complaints,NaN,NaN,40.0,Pending,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6997,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6998,Low-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6999,Moderate-Risk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [ ]:
final = pd.concat([out3,df],axis=1)

In [ ]:
final

,Customer_ID,Age,Agent_ID,Agent_Notes,Authorization_Code,Avg_Monthly_Spend,Balance_Transferred,Billing_Cycle,Card_Cancelled,Card_Expiry_Date,...,Open_Email_Rate,Days_Since_Last_Login,Num_Complaints,Days_Since_Last_Transaction,Annual_Fee,Resolution_Status,Credit_Utilization_Rate,Installment_Plan,Customer_Acquisition_Date,Interaction_ID_Count
0,c1000,55,4485,None,None,394.078893,4735.745674,None,Yes,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,c1001,20,4854,None,None,729.949036,257.509881,None,Yes,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,c1002,71,1842,None,None,297.217360,2179.414873,None,No,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,c1003,46,6415,None,None,1479.906741,3486.984928,None,Yes,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,c1004,57,4403,None,None,192.544863,4608.290614,None,Yes,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,c7995,40,5632,None,None,1709.557215,4338.030705,None,No,None,...,NaN,NaN,NaN,NaN,NaN,NaN,0.80457,NaN,NaT,NaN
6996,c7996,70,4017,None,None,1863.783314,390.024807,None,Yes,None,...,0.068839,314.0,46.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6997,c7997,19,2019,None,None,1255.407955,1391.424388,None,No,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6998,c7998,23,7545,None,None,1487.266006,2703.481602,None,Yes,None,...,0.021831,258.0,28.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6999,c7999,55,4118,None,None,570.797422,4630.362409,None,Yes,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
df = out3